version: '3'
services:
  postgres:
    build:
      context: .
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: